name = "short-uri-api"
main = "api/index.ts"
compatibility_date = "2024-07-18"

kv_namespaces = [
  { binding = "SHORT_URI_KV", id = "your-production-kv-namespace-id", preview_id = "your-preview-kv-namespace-id" }
]

[vars]
JWT_SECRET = "your-jwt-secret"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "your-secure-password"
